### PR TITLE
default to English if lang param is invalid

### PR DESCRIPTION
**Pull request by zeke**
Fixes 500 errors for requests like`//index.php?lang=Cn&index=0000`

image

### CODE REVIEW

**Comment by FranzDeCopenhague** [comment]
@Zeke this change may have an impact on https://github.com/electron/electronjs.org/issues/1107
https://github.com/electron/electronjs.org/blob/master/middleware/lang-resolver.js

**Comment by zeke** [comment]
The `langResolver` middleware is before the `contextBuilder`, so it's executed first. We should be good:

https://github.com/electron/electronjs.org/blob/1adcb8c362c16e104a687179536b263a7cca8b1e/server.js#L57-L58

Also you wrote a bunch of tests for language resolution, correct? If they were affected we'd see some test failures.

**Comment by FranzDeCopenhague** [comment]
Yes, you are right, all checks have passed

**Comment by FranzDeCopenhague** [comment]
This is the first time I do merge a pull request. Do I have to click on "Delete branch" button as well?

**Comment by codebytere** [comment]
@FranzDeCopenhague it's not required, but it helps to keep the branch list clean and tidy

**Comment by FranzDeCopenhague** [comment]
@codebytere Thank you!

**Pull request merged**
