### PR TITLE
feat: add a download cta for fiddle

### LINKED ISSUE #4484: Add a download CTA for Fiddle at the top of the page
Currently, there's no CTA to download Fiddle at the top of the page under the logo... it's only marketing copy with the CTA at the bottom. It would be nice if the top also had a download CTA to push people to download first 👍🏻

### PR DESCRIPTION
**Pull request by azhsetiawan**
Resolve #4484 

Add 2 CTA options
- icon in header
- section below hero

image
image

### CODE REVIEW

**Review by erickzhao — COMMENTED** [review]
I originally thought that the linked issue was to add the CTA on top for [electronjs.org/fiddle](https://www.electronjs.org/fiddle)  rather than the homepage.

cc @bnb wondering if you could clarify

**Comment by bnb** [comment]
Yep, @erickzhao you're correct - specifically meant it to be on the Fiddle page.

**Comment by erickzhao** [comment]
Hey @azhsetiawan, following up again to ask if you were still interested in working on this with the requested changes above? :)

**Comment by erickzhao** [comment]
@azhsetiawan Following up again. Are you still interested in completing this PR?

**Pull request closed without merging**
