### PR TITLE
fix: truncating for download block

### PR DESCRIPTION
**Pull request by HashimotoYT**
Fixing https://github.com/electron/electronjs.org/pull/1778#issuecomment-452908909

| Before | After |
| --- | --- |
| before | after

### CODE REVIEW

**Comment by BinaryMuse** [comment]
Oh I just noticed the "see all 11 files" at the bottom of the sidebar. Was the original intent for the buttons to clip? 🤔

**Comment by BinaryMuse** [comment]
@HashimotoYT I'm sorry, I didn't mean your original PR, but the original styling for the website. The link to "View all 11 files" only makes sense if we're not already showing all 11 files.

**Comment by HashimotoYT** [comment]
It's true, we don't show all 11 files, we only show platform specific files, how seed below. All files described here displayed by deleting "display: none" style.

name

**Comment by BinaryMuse** [comment]
Ah, I see. Thanks for clarifying.

I think this looks good to me!

**Pull request merged**
