### PR TITLE
In-app purchases blog post

### PR DESCRIPTION
**Pull request by zeke**
Made some progress on this today, but I'm not totally happy with it yet. Feedback, please!

@AdrienFery @codebytere @vanessayuenn @ckerr @groundwater

### CODE REVIEW

**Comment by zeke** [comment]
See also https://github.com/electron/apps/pull/600

**Comment by AdrienFery** [comment]
Thank you very much for this great article @zeke !

Here is some edit suggestions.

### Suggestion 1 (in bold)
> The new API was added to Electron by community contributor Adrien Fery to enable in-app purchases in Amanote, a note-taking Electron app built for students. Amanote is free to download, and includes features like mathematical formulae, LaTeX, synchronizing audio to slides, and more.

The new API was added to Electron by community contributor Adrien Fery to enable in-app purchases in Amanote, a note-taking Electron app **for lectures and conferences**. Amanote is free to download, and **allows to take clear and structured notes on PDFs with features like mathematical formulae, drawings, audio recording,** and more.

### Suggestion 2
In the considerations section, you can maybe add that Apple handles geographical pricing automatically which can be hard to set-up oneself.

**Comment by zeke** [comment]
@AdrienFery do you have something we can link to about how Apple doesn't allow third-party checkout systems?

**Comment by AdrienFery** [comment]
@zeke Here is a link: [https://developer.apple.com/app-store/review/guidelines/#payments](https://developer.apple.com/app-store/review/guidelines/#payments)

> If you want to unlock features or functionality within your app, (by way of example: subscriptions, in-game currencies, game levels, access to premium content, or unlocking a full version), **you must use in-app purchase**.

**Remark**: Apple doesn't allow third-party checkout systems for apps on the App Store. Apps outside the App Store can use third-party checkout systems.

**Comment by zeke** [comment]
@AdrienFery I changed the wording around Amanote, per your suggestion.

To keep this post positive and celebratory, I have decided to remove the "considerations" section that mentions things like the 30% cut taken by Apple and Microsoft, and Apple's restrictions around third-party checkout systems. I still think these points are important for developers to consider though, so once https://github.com/electron/electron/pull/12464 lands, I will follow up with a PR that adds this information to the `inAppPurchase` tutorial page.

**Comment by zeke** [comment]
Rendered: https://electron-website-pr-1218.herokuapp.com/blog/in-app-purchases

Lifting the WIP status. I think this is ready to go.

**Comment by AdrienFery** [comment]
@zeke Perfect !

**Pull request merged**
