### PR TITLE
Link to search from nav bar

### PR DESCRIPTION
**Pull request by vanessayuenn**
This will make the `/search` route accessible to public! 🎉  Also, I improved the description a bit to be more explicit about which data source the users are searching within.

### CODE REVIEW

**Comment by zeke** [comment]
Hey I took the liberty of making some stylistic tweaks:

- turned headings into links
- added octicons to headings
- made results more compact, with one line of text per result
- lowered opacity for stuff that doesn't need to be loud, like result counts

Here's what it looks like now:

screen shot 2018-01-23 at 8 24 46 pm

**Comment by zeke** [comment]
Passing the review baton back to you, @vanessayuenn 🤝

**Comment by pierreneter** [comment]
`span.label` influences the `label` of the `button` at the homepage. Just remove `class="label"` at home to fix it. I will push a commit.

snap1

**Comment by vanessayuenn** [comment]
Niceeeee! That looks great @zeke. 💯 
image

**Pull request merged**
