### PR TITLE
Handle empty search result set

### PR DESCRIPTION
**Pull request by zeke**
The website went down for a bit today. To fix it, I rolled back to a previous version on Heroku.

This is an exploratory PR to help diagnose if something is wrong with the `master` branch.

### CODE REVIEW

**Comment by zeke** [comment]
This PR doesn't differ from master and the deployment on Heroku is running just fine... 🤔

**Comment by codebytere** [comment]
there was a crash again for about an hour last night too, around 8:30pm

**Comment by zeke** [comment]
@vanessayuenn tracked down a probable cause:

```
Feb 07 19:14:46 electron-website app/web.1: TypeError: Cannot read property 'length' of null 
Feb 07 19:14:46 electron-website app/web.1:     at Promise.all.searchOps.map (/app/routes/search/index.js:35:47) 
Feb 07 19:14:46 electron-website app/web.1:     at <anonymous> 
Feb 07 19:14:46 electron-website app/web.1: npm ERR! code ELIFECYCLE 
Feb 07 19:14:46 electron-website app/web.1: npm ERR! errno 1 
Feb 07 19:14:46 electron-website app/web.1: npm ERR! electronjs.org@2.0.0 start: `cross-env NODE_PATH=. NODE_ENV=production node server.js` 
Feb 07 19:14:46 electron-website app/web.1: npm ERR! Exit status 1 
Feb 07 19:14:46 electron-website app/web.1: npm ERR!  
```

**Comment by zeke** [comment]
This is a query that kills it:

```
/search?q=*
```

**Comment by MarshallOfSound** [comment]
This patch should handle that error, it looks like we handle missing results for the `results` key but not for the `resultsNum` key

```
diff --git a/routes/search/index.js b/routes/search/index.js
index 46ab389c..9b615c39 100644
--- a/routes/search/index.js
+++ b/routes/search/index.js
@@ -32,7 +32,7 @@ module.exports = (req, res) => {
     return {
       searchOp,
       // FIXME: use real pagination
-      resultsNum: results.data[searchOp.name].length,
+      resultsNum: results.data[searchOp.name] ? results.data[searchOp.name].length : 0,
       results: (req.params.searchIn || req.query.json !== undefined)
                 ? results.data[searchOp.name] : results.data[searchOp.name].slice(0, 5)
     }
```

**Comment by zeke** [comment]
Thanks for sleuthing, @codebytere, @vanessayuenn, and @MarshallOfSound. I've committed a fix here.

**Comment by vanessayuenn** [comment]
I could still reproduce crash with the same query 😢. I have added another patch at #1094.

**Pull request merged**
