### PR TITLE
feat: upgrade Octicons to 8.3.0

### PR DESCRIPTION
**Pull request by HashimotoYT**
This PR updates Octicons to 8.3.0 version, adds a script for automatic updating and removes old Bower Octicons. It uses [icon-font-generator](https://github.com/Workshape/icon-font-generator) for generating icon font.

New icons:

`requested-changes`
`fold-up`
`fold-down`
`eye-closed`
`arrow-both`
`archive`
`kebab-horizontal`
`kebab-vertical`
`project`
`note`
`scrren-full`
`screen-normal`
`grabber`
`plus-small`

### CODE REVIEW

**Comment by BinaryMuse** [comment]
This looks great! I pushed a couple small changes, feel free to take a look and see what you think. If it looks good to you, I say ship it

**Comment by HashimotoYT** [comment]
It looks pretty. I will soon create documentation on how to use it. So, yes some 🕐.

**Comment by HashimotoYT** [comment]
Argh, an angry out-of-date queue, I do not have time to get into it 🐹

**Comment by BinaryMuse** [comment]
Yeah, the auto-merging makes that sort of a pain. Maybe it's something we should rethink 🤔

**Pull request merged**
