### PR TITLE
fix: Added Latest Release information in app list

### LINKED ISSUE #1148: Show app’s “last updated”
In the list of Electron apps, there is a `Added (x <time>) ago` bit of info in the long list view.

Many of these apps were added 2 years ago, which can give the appearance of staleness.  

Instead, I’d love to see this same info show when each app was last **updated**.

### PR DESCRIPTION
**Pull request by parasg1999**
I have added the `Latest Release` information in the app list page as discussed in #1148. The following are the results.
- When latest release information is available
Screenshot from 2020-05-30 21-39-02
- When latest release information is not available
Screenshot from 2020-05-30 21-40-06

Would be glad to receive suggestions and make changes.
closes #1148

### CODE REVIEW

**Comment by parasg1999** [comment]
ping @HashimotoYT

**Comment by erickzhao** [comment]
I can also give this a look today :)

**Comment by parasg1999** [comment]
@erickzhao Thanks a lot!

**Comment by parasg1999** [comment]
@erickzhao Makes sense! Would you like me to implement that?

**Comment by HashimotoYT** [comment]
@erickzhao 👍. All other looks good.

**Comment by parasg1999** [comment]
@HashimotoYT @erickzhao I have made the changes as per you comments. Please review.

Screenshot from 2020-06-02 22-53-29
Screenshot from 2020-06-02 22-53-47

**Comment by HashimotoYT** [comment]
@parasg1999 Can you please fix merge conflicts

**Comment by parasg1999** [comment]
@HashimotoY Roselved!

**Comment by parasg1999** [comment]
Thanks a lot! @HashimotoYT 🤩

**Pull request merged**
