### PR TITLE
Fix for #1107 Do not redirect with a valid language query param

### PR DESCRIPTION
**Pull request by FranzDeCopenhague**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the quick fix, @FranzDeCopenhague!

In the future, please ping someone else for review before shipping changes.

**Comment by FranzDeCopenhague** [comment]
Sure, It was my first contribution and I am still learning the ropes

**Comment by zeke** [comment]
No worries!

**Comment by zeke** [comment]
As a precaution, I went ahead and flipped this switch to require PR reviews:

image

**Pull request merged**
