### PR TITLE
feat: create landing page for Electron Fiddle

### PR DESCRIPTION
**Pull request by HashimotoYT**
This PR creates landing page for Electron Fiddle application.

## How it look:

localhost_5000_fiddle

What do you think about this page @felixrieseberg.

## The small todo list:

- [x] Add localization strings.
- [x] Create Cypress test
- [x] Create mocha test

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Ohhhhhhhh 👏

**Comment by felixrieseberg** [comment]
Ohhhhhhhh 👏 One thing, real quick: I'm sure you saw that there's going to be a new icon (https://github.com/electron/fiddle/issues/117) and I suggest that we launch the website together with the next version?

**Comment by HashimotoYT** [comment]
I support the proposal to launch this with the release of the new version.

**Comment by simurai** [comment]
@HashimotoYT I hope you don't mind me pushing straight to this PR. 😇 I replaced the logo to match the [Devtron](https://electronjs.org/devtron) and [Spectron](https://electronjs.org/spectron) pages.

**Comment by felixrieseberg** [comment]
Alright, I think we can move forward here! We should make new screenshots with the updated UI elements but we’re otherwise ready :rocket:

**Comment by felixrieseberg** [comment]
I am! We'll have to update screenshots, but that's on my todo list for all properties 👯‍♂️

**Pull request merged**
