### PR TITLE
add lang query param and document it in contributing

### PR DESCRIPTION
**Pull request by zeke**
This PR is a followup to https://github.com/electron/electronjs.org/pull/1031 that changes the one-off param from `language` to `lang` to avoid stepping on the toes of the existing default `language` query param name that [`express-request-language` allows](https://github.com/tinganho/express-request-language/blob/master/README.md#queryname-optional-object). This also adds docs to CONTRIBUTING.md so folks know they can assemble shareable translated URLs.

### CODE REVIEW

**Comment by zeke** [comment]
For some reason the use of `supertest-session` is causing the tests to hang, even though they're passing.

**Comment by zeke** [comment]
> We should consider incorporating that into the UI

Yeah I was thinking that too. "View this page in..."

**Comment by zeke** [comment]
@rjs was kind enough to publish a [fix](https://github.com/rjz/supertest-session/issues/28) to supertest-session. This should go green now.

**Comment by vanessayuenn** [comment]
@zeke the `package-lock.json` was causing `npm i` to fail at updating `supertest-session` for some reason. It looks ok now, so merging this PR. :)

**Pull request merged**
